version: "3.8"
services:
  mysql:
    image: mysql:8.3.0
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file: ../.env
    volumes:
      - go-sqlc-mysql-sample-db-store:/var/lib/mysql

volumes:
  go-sqlc-mysql-sample-db-store:
