name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=5m ./...

      - name: Test
        env:
          TEST_MYSQL_DATABASE: ${{ vars.TEST_MYSQL_DATABASE }}
          TEST_MYSQL_ROOT_PASSWORD: ${{ vars.TEST_MYSQL_ROOT_PASSWORD }}
          TEST_MYSQL_USER: ${{ vars.TEST_MYSQL_USER }}
          TEST_MYSQL_PASSWORD: ${{ vars.TEST_MYSQL_PASSWORD }}
          TEST_MYSQL_HOST: ${{ vars.TEST_MYSQL_HOST }}
          TEST_MYSQL_TCP_PORT: ${{ vars.TEST_MYSQL_TCP_PORT }}
        run: >
          TEST_MYSQL_DATABASE=${TEST_MYSQL_DATABASE}
          TEST_MYSQL_ROOT_PASSWORD=${TEST_MYSQL_ROOT_PASSWORD}
          TEST_MYSQL_USER=${TEST_MYSQL_USER}
          TEST_MYSQL_PASSWORD=${TEST_MYSQL_PASSWORD}
          TEST_MYSQL_HOST=${TEST_MYSQL_HOST}
          TEST_MYSQL_TCP_PORT=${TEST_MYSQL_TCP_PORT}
          go test -race ./...
